@startuml
'https://plantuml.com/class-diagram

class Client {
    +calculer(int nbParties):ImageCalcul
}

class ServiceCalcul {
    +calculer(Calcul calcul) : void
    +estDispo() : boolean
}

class ImageCalcul {
    List<Calcul> calculs
}

class Calcul {
    Image image
    int id
    Image resultat
}

class Server {
    +demanderCalcul(Image image, int nbCalc) : Calcul
}

ServiceCalcul <-- Calcul
Client <-- ServiceCalcul
Client <-- ImageCalcul
Client <-- Calcul
Calcul <-- ImageCalcul


@enduml