@startuml
'https://plantuml.com/class-diagram

class Client {
    calculer(int nbParties):void
    display():void
}

class Server {
    demanderCalcul():void
    ajouterCalcul():void
    supprimerCalcul():void
}

class ServiceCalcul {
    calculer(Scene scene, Coordonnees coordonnees)
}

Client <- ServiceCalcul : image, coordonnees
ServiceCalcul <- Client : scene, coordonnees

Server <-- Client : demanderCalcul
Client <-- Server : serviceCalcul
Server <-- Client : supprimerCalcul

@enduml